[package]
name = "staart"
version = "0.1.4"
authors = ["Anthony Martinez <anthony@ajmartinez.com>"]
edition = "2018"
license = "GPL-3.0+"
readme = "README.md"
homepage = "https://gitlab.com/anthonyjmartinez/staart"
repository = "https://gitlab.com/anthonyjmartinez/staart.git"
description = "A Rust implementation of a tail-like library and binary crate"
keywords = ["tail"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
panic = 'abort'

